CREATE OR REPLACE TABLE `meli-bi-data.EXPLOTACION.DM_MKP_ORDERS_MSTR`
PARTITION BY FECHA_SERVER 
CLUSTER BY SIT_SITE_ID, VERTICAL, CAT_L1_ID
AS (



WITH ORDERS AS (

select
o.sit_site_id
, DATE(ORD_CLOSED_DTTM) FECHA_SERVER
, case WHEN O.SIT_SITE_ID ='MLA' then DATE(DATETIME(TIMESTAMP_ADD(ORD_CLOSED_DTTM, INTERVAL 4 HOUR), "America/Argentina/Buenos_Aires"))
    WHEN O.SIT_SITE_ID ='MLC' then DATE(DATETIME(TIMESTAMP_ADD(ORD_CLOSED_DTTM, INTERVAL 4 HOUR), "America/Santiago"))
    WHEN O.SIT_SITE_ID ='MLB' then DATE(DATETIME(TIMESTAMP_ADD(ORD_CLOSED_DTTM, INTERVAL 4 HOUR), "Brazil/East"))
    WHEN O.SIT_SITE_ID ='MLM' then DATE(DATETIME(TIMESTAMP_ADD(ORD_CLOSED_DTTM, INTERVAL 4 HOUR), "Mexico/General"))
    WHEN O.SIT_SITE_ID ='MLU' then DATE(DATETIME(TIMESTAMP_ADD(ORD_CLOSED_DTTM, INTERVAL 4 HOUR), "America/Montevideo"))
    WHEN O.SIT_SITE_ID ='MCO' then DATE(DATETIME(TIMESTAMP_ADD(ORD_CLOSED_DTTM, INTERVAL 4 HOUR), "America/Bogota"))
    WHEN O.SIT_SITE_ID ='MPE' then DATE(DATETIME(TIMESTAMP_ADD(ORD_CLOSED_DTTM, INTERVAL 4 HOUR), "America/Lima"))
    WHEN O.SIT_SITE_ID ='MLV' then DATE(DATETIME(TIMESTAMP_ADD(ORD_CLOSED_DTTM, INTERVAL 4 HOUR), "America/Caracas"))
  END FECHA_SITE
, ORD_CATEGORY.LEVELS[SAFE_OFFSET(0)].ID CAT_L1_ID
, ORD_CATEGORY.LEVELS[SAFE_OFFSET(0)].NAME CAT_L1_NAME
, ORD_CATEGORY.LEVELS[SAFE_OFFSET(1)].ID CAT_L2_ID
, ORD_CATEGORY.LEVELS[SAFE_OFFSET(1)].NAME CAT_L2_NAME
, ORD_CATEGORY.LEVELS[SAFE_OFFSET(2)].ID CAT_L3_ID
, ORD_CATEGORY.LEVELS[SAFE_OFFSET(2)].NAME CAT_L3_NAME
, ORD_CATEGORY.ID CAT_L7_ID
, DOM_DOMAIN_ID as ORDER_DOMAIN
, ORD_SELLER.ID as CUS_CUST_ID_SEL
, ORD_SELLER.REPUTATION_LEVEL
, ORD_SELLER.POWER_STATUS
, ORD_SELLER.OFFICIAL_STORE_ID
, ORD_ITEM.ID as ITE_ITEM_ID
, ORD_ITEM.TITLE as ITE_ITEM_TITLE
, ORD_ITEM.CONDITION as ITEM_CONDITION

,CASE WHEN ORD_SHIPPING.LOGISTIC_TYPE = 'drop_off' then 'DS'
  WHEN ORD_SHIPPING.LOGISTIC_TYPE = 'xd_drop_off' then 'XD'
  WHEN ORD_SHIPPING.LOGISTIC_TYPE = 'cross_docking' then 'XD'
  WHEN ORD_SHIPPING.LOGISTIC_TYPE = 'fulfillment' then 'FBM'
  WHEN ORD_SHIPPING.LOGISTIC_TYPE = 'self_service' then 'FLEX'
  ELSE 'Otro' 
end as LOGISTIC_TYPE

, SUM(CASE WHEN ORD_TGMV_FLG is TRUE THEN o.ORD_ITEM.QTY * o.ORD_ITEM.unit_price else 0 end) AS TGMV_LOC
, SUM(CASE WHEN ORD_TGMV_FLG is TRUE THEN o.ORD_ITEM.QTY * o.ORD_ITEM.unit_price * o.CC_USD_RATIO else 0 end) AS TGMV
, SUM(CASE WHEN ORD_TGMV_FLG is TRUE THEN o.ORD_ITEM.QTY else 0 end) AS TSI

, SUM(o.ORD_ITEM.QTY * o.ORD_ITEM.unit_price) AS GMV_LOC
, SUM(o.ORD_ITEM.QTY * o.ORD_ITEM.unit_price * o.CC_USD_RATIO) AS GMV
, SUM(o.ORD_ITEM.QTY) AS SI

, count(distinct ord_order_id) as TXS

from `meli-bi-data.WHOWNER.BT_ORD_ORDERS` as o

where 1=1
and o.SIT_SITE_ID = 'MLC'
and o.ORD_CLOSED_DTTM >= cast('2020-01-01' as timestamp)-- cast(TIMESTAMP_SUB(CURRENT_DATE(), INTERVAL 46 DAY) as timestamp)
and o.ORD_GMV_FLG is true

GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19

), ITEMS as (

 SELECT SIT_SITE_ID SIT_SITE_ID
, ITE_ITEM_ID ITE_ITEM_ID
-- , ITE_ITEM_TITLE ITEM_TITLE
-- ,- ITE_ITEM_QUANTITY_AVAILABLE STOCK
-- , ITE_ITEM_STATUS STATUS
-- , ITE_ITEM_CONDITION CONDITION
-- , CASE WHEN ITE_ITEM_SHIPPING_PAYMENT_TYPE_ID = 'free_shipping' THEN TRUE ELSE FALSE END FS_ITEM
-- , CASE WHEN SIT_SITE_ID = 'MLC' THEN TRUE
--    WHEN SIT_SITE_ID = 'MLU' AND ITE_ITEM_LISTING_TYPE_ID_NW <> 'free' THEN TRUE
--   WHEN SIT_SITE_ID = 'MLV' THEN FALSE
--   WHEN ITE_ITEM_LISTING_TYPE_ID_NW = 'gold_pro' THEN TRUE 
--   ELSE FALSE 
--  END PSJ_ITEM
, ITE_ITEM_CATALOG_PRODUCT_ID PRODUCT_ID
, ITE_ITEM_THUMBNAIL THUMBNAIL
, ITE_ITEM_PERMALINK PERMALINK
, SUBSTR(ITE_ITEM_DOM_DOMAIN_ID,5) as DOM_DOMAIN_ID

FROM `meli-bi-data.WHOWNER.LK_ITE_ITEMS`
WHERE IS_TEST = FALSE
AND SIT_SITE_ID IN ('MLC')
AND ITE_ITEM_ID IN (SELECT ITE_ITEM_ID FROM ORDERS)

), ITEM_ATTRS AS (
 SELECT I.SIT_SITE_ID
, ITE_ITEM_ID
, MIN(CASE WHEN ATTR.ID = 'BRAND' THEN ATTR.VALUE_NAME END) AS BRAND
, MIN(CASE WHEN ATTR.ID = 'SELLER_SKU' THEN ATTR.VALUE_NAME END) AS SKU
  FROM `meli-bi-data.WHOWNER.LK_ITE_ITEMS` I, UNNEST(ITE_ITEM_ATTRIBUTES) AS ATTR
  WHERE IS_TEST = FALSE
  AND ITE_ITEM_ID IN (SELECT ITE_ITEM_ID FROM ORDERS)
  AND SIT_SITE_ID IN ('MLA','MLC','MLB','MLM','MLU','MCO','MPE','MLV')
  AND ATTR.ID IN ('BRAND','SELLER_SKU')
  GROUP BY 1,2

), DOMAINS as (

select
d.SIT_SITE_ID
, d.VERTICAL 
, d.DOM_DOMAIN_AGG1
, d.DOM_DOMAIN_AGG2
, d.DOM_DOMAIN_AGG3
, SUBSTR(d.DOM_DOMAIN_ID,5) as DOM_DOMAIN_ID -- quitamos el SITE_ID y "-" : "MLC-"


FROM `meli-bi-data.WHOWNER.LK_DOM_DOMAINS` as d

), SEGMENTS as (

select
trim(s.SIT_SITE_ID) as SIT_SITE_ID
, s.CUS_CUST_ID_SEL
, s.CUS_NICKNAME
, s.SEGMENTO
, s.SEGMENTO_SELLER_DETAIL
, s.MLIDER_FLAG
, s.TIPOFOCO
, case
   when s.segmento_seller_detail = 'PRIVATE LABEL' THEN 'PL'
   when s.segmento_seller_detail = 'FIRST PARTY' THEN '1P'
   when s.segmento_seller_detail like '%CBT%'then 'CBT'
   when s.segmento = 'TO' then 'TO'
   when s.segmento = 'CARTERA GESTIONADA' then 'CG'
   when s.segmento = 'MIDTAIL' then 'MT'
   else 'LT'
  end as SEGMENTO_FIX

FROM `meli-bi-data.WHOWNER.LK_MKP_SEGMENTO_SELLERS` as s

), PRICES AS (
      SELECT I.SIT_SITE_ID,
        I.ITE_ITEM_ID,
        MIN(ITE_ITEM_PRICE_AMOUNT) PRICE,
        MIN(ITE_ITEM_PRICE_REGULAR_AMOUNT) REGULAR_PRICE
      FROM `meli-bi-data.WHOWNER.LK_ITE_ITEM_PRICES` I
      WHERE ITE_ITEM_PRICE_API_STATUS = 'ACTIVE'
        AND (TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 4 HOUR) BETWEEN ITE_ITEM_PRICE_START_TIME_DTTM AND ITE_ITEM_PRICE_END_TIME_DTTM
          OR ITE_ITEM_PRICE_TYPE = 'standard')
        AND ITE_ITEM_ID IN (SELECT ITE_ITEM_ID FROM ORDERS)
        AND SIT_SITE_ID IN ('MLC')
      GROUP BY 1,2
    ), ORDERS_DETAILS as (

select 
o.*
, s.CUS_NICKNAME
, s.MLIDER_FLAG
, d.VERTICAL 
, d.DOM_DOMAIN_AGG1
, d.DOM_DOMAIN_AGG2
, d.DOM_DOMAIN_AGG3
, s.SEGMENTO_FIX
, s.TIPOFOCO
, case 
   when SEGMENTO_FIX in ('1P','PL','CBT') then SEGMENTO_FIX 
   ELSE '3P' 
  END as BU
-- , i.stock
-- , i.status as item_status
-- , i.fs_item
-- , i.PSJ_ITEM
, i.PRODUCT_ID
, i.PERMALINK
, p.PRICE
, p.REGULAR_PRICE
, a.BRAND
, a.SKU
, DATE_TRUNC(o.FECHA_SERVER, WEEK(MONDAY)) as WEEK_SERVER
, DATE_TRUNC(o.FECHA_SITE, WEEK(MONDAY)) as WEEK_SITE
-- , case
--   when  (s.segmento_seller_detail in ('PRIVATE LABEL','FIRST PARTY') or s.segmento = 'TO') THEN o.OFFICIAL_STORE_ID
--   else null
--  end as STORE_ID

FROM ORDERS as o
left join ITEMS as i on o.sit_site_id = i.sit_site_id and o.ite_item_id = i.ite_item_id
left join DOMAINS as d on i.sit_site_id = d.sit_site_id and i.DOM_DOMAIN_ID = d.DOM_DOMAIN_ID
left join SEGMENTS as s on o.sit_site_id = s.sit_site_id and o.cus_cust_id_sel = s.cus_cust_id_sel
left join PRICES as p on o.sit_site_id = p.sit_site_id and o.ite_item_id = p.ite_item_id
left join ITEM_ATTRS as a on o.sit_site_id = a.sit_site_id and o.ite_item_id = a.ite_item_id
)

select * from ORDERS_DETAILS


)


